# Master keyword list for D&J Deal Radar
# Broad category coverage with resale-safe query variety to reduce repeated junk.

SEARCH_TERMS = [
    # Phones / Apple / Samsung / Android
    "iphone",
    "iphone 16",
    "iphone 15",
    "iphone 14",
    "iphone 13",
    "iphone 12",
    "iphone 11",
    "iphone pro max",
    "iphone plus",
    "iphone unlocked",
    "iphone lot",
    "iphone bundle",
    "broken iphone",
    "iphone cracked",
    "iphone for parts",
    "iphone parts",
    "samsung galaxy",
    "galaxy s24",
    "galaxy s23",
    "galaxy ultra",
    "samsung phone",
    "android phone",
    "pixel phone",
    "google pixel",
    "oneplus phone",

    # Tablets / laptops / desktop / components
    "ipad",
    "ipad pro",
    "ipad air",
    "tablet",
    "tablet lot",
    "macbook",
    "macbook pro",
    "macbook air",
    "gaming laptop",
    "laptop lot",
    "computer bundle",
    "desktop computer",
    "gaming pc",
    "pc bundle",
    "pc parts",
    "graphics card",
    "gpu",
    "rtx",
    "gtx",
    "nvidia",
    "amd gpu",
    "monitor",
    "monitor lot",

    # Consoles / gaming hardware
    "ps5",
    "ps4",
    "playstation",
    "playstaton",
    "ps5 bundle",
    "ps4 bundle",
    "xbox",
    "xbox one",
    "xbox series x",
    "xbox series s",
    "xobx",
    "xbox bundle",
    "nintendo switch",
    "switch oled",
    "switch bundle",
    "nintndo",
    "gamecube",
    "wii",
    "retro console",
    "retro gaming",
    "gaming bundle",

    # Cards / collectibles / hobby
    "pokemon",
    "pokemon cards",
    "pokemon lot",
    "sports cards",
    "card collection",
    "card lot",
    "trading cards",
    "michael jordan cards",
    "baseball cards",
    "basketball cards",
    "football cards",
    "hockey cards",
    "sealed games",
    "retro games",
    "video game lot",
    "game lot",
    "lego lot",
    "hot wheels lot",
    "funko lot",
    "rc car",
    "drone lot",
    "collectibles",
    "model kits",

    # Tools / garage / contractor
    "milwaukee",
    "dewalt",
    "makita",
    "snap on",
    "snapon",
    "craftsman tools",
    "power tools",
    "tool lot",
    "tool bundle",
    "mechanic tools",
    "impact driver",
    "impact wrench",
    "cordless drill",
    "socket set",
    "air compressor",
    "tool box",
    "rolling toolbox",
    "shop tools",
    "garage tools",
    "sawzall",
    "compressor",
    "generator",

    # Cameras / audio / electronics / music gear
    "camera lot",
    "dslr",
    "canon camera",
    "nikon",
    "sony camera",
    "gopro",
    "speaker",
    "bluetooth speaker",
    "stereo equipment",
    "receiver",
    "dj equipment",
    "mixer",
    "amp",
    "electronics lot",
    "random electronics",

    # Watches / jewelry / small valuables
    "watch lot",
    "smart watch",
    "apple watch",
    "gold jewelry",
    "silver jewelry",
    "jewelry lot",

    # Liquidation / urgency / broad opportunity
    "garage sale",
    "estate sale",
    "moving sale",
    "yard sale",
    "garage cleanout",
    "storage cleanout",
    "basement cleanout",
    "attic cleanout",
    "everything must go",
    "need gone",
    "must sell",
    "make offer",
    "pickup today",
    "today only",
    "cheap",
    "obo",
    "best offer",
    "bulk lot",
    "mixed lot",
    "bundle",
    "box of stuff",
    "garage find",
    "attic find",
    "storage unit",

    # Repair / damaged / underpriced leads
    "for parts",
    "doesnt work",
    "not working",
    "broken",
    "cracked screen",
    "needs repair",
    "not tested",
    "as is",
    "repair lot",
    "electronics repair",
    "parts lot",

    # Misspellings / hidden listings
    "iphon",
    "iphne",
    "ipone",
    "playstaton",
    "playstion",
    "pokeman",
    "pokmon",
    "nintndo",
    "xobx",
    "garag sale",
    "estste sale",
    "movng sale",
    "macbok",
    "labtop",
]
