# Master keyword list for D&J Deal Radar
# Expanded category coverage to reduce repeat hits and surface broader deal types.

SEARCH_TERMS = [
    # Phones / Apple / Samsung
    "iphone",
    "iphone 16",
    "iphone 15",
    "iphone 14",
    "iphone 13",
    "iphone 12",
    "iphone 11",
    "iphone pro max",
    "iphone plus",
    "iphone unlocked",
    "iphone lot",
    "iphone bundle",
    "broken iphone",
    "iphone cracked",
    "iphone for parts",
    "iphone parts",
    "samsung galaxy",
    "galaxy s23",
    "galaxy s24",
    "samsung phone",
    "android phone",
    "pixel phone",
    "google pixel",
    "oneplus",

    # Tablets / laptops / computers
    "ipad",
    "ipad pro",
    "ipad air",
    "tablet",
    "tablet lot",
    "macbook",
    "macbook pro",
    "macbook air",
    "gaming laptop",
    "laptop lot",
    "computer bundle",
    "desktop computer",
    "gaming pc",
    "pc parts",
    "graphics card",
    "gpu",
    "rtx",
    "gtx",
    "nvidia",
    "amd gpu",
    "monitor",
    "monitor lot",

    # Consoles / gaming hardware
    "ps5",
    "ps4",
    "playstation",
    "playstaton",
    "ps5 bundle",
    "ps4 bundle",
    "xbox",
    "xbox one",
    "xbox series x",
    "xbox series s",
    "xobx",
    "xbox bundle",
    "nintendo switch",
    "switch oled",
    "switch bundle",
    "nintndo",
    "gamecube",
    "wii",
    "retro console",
    "retro gaming",
    "controller lot",
    "gaming bundle",

    # Video games / collectibles crossover
    "pokemon",
    "pokemon cards",
    "pokemon lot",
    "sports cards",
    "card collection",
    "card lot",
    "trading cards",
    "michael jordan cards",
    "baseball cards",
    "basketball cards",
    "football cards",
    "hockey cards",
    "vintage cards",
    "sealed games",
    "retro games",
    "video game lot",
    "game lot",

    # Tools / garage / contractor
    "milwaukee",
    "dewalt",
    "makita",
    "snap on",
    "snapon",
    "craftsman tools",
    "power tools",
    "tool lot",
    "tool bundle",
    "mechanic tools",
    "impact driver",
    "impact wrench",
    "cordless drill",
    "socket set",
    "air compressor",
    "tool box",
    "rolling toolbox",
    "shop tools",
    "garage tools",
    "sawzall",
    "compressor",
    "generator",

    # Cameras / audio / electronics
    "camera lot",
    "dslr",
    "canon camera",
    "nikon",
    "gopro",
    "speaker",
    "bluetooth speaker",
    "stereo equipment",
    "receiver",
    "dj equipment",
    "electronics lot",
    "random electronics",

    # Watches / jewelry / luxury-ish quick flips
    "watch lot",
    "smart watch",
    "apple watch",
    "gold jewelry",
    "silver jewelry",
    "jewelry lot",

    # Toys / hobby / resale-friendly extras
    "lego lot",
    "rc car",
    "drones",
    "collectibles",
    "funko lot",
    "hot wheels lot",
    "model kits",

    # Liquidation / urgency / broad opportunity
    "garage sale",
    "estate sale",
    "moving sale",
    "yard sale",
    "garage cleanout",
    "storage cleanout",
    "basement cleanout",
    "attic cleanout",
    "everything must go",
    "need gone",
    "must sell",
    "make offer",
    "pickup today",
    "today only",
    "cheap",
    "obo",
    "best offer",
    "bulk lot",
    "mixed lot",
    "bundle",
    "box of stuff",
    "garage find",
    "attic find",
    "storage unit",

    # Repair / damaged / underpriced leads
    "for parts",
    "doesnt work",
    "not working",
    "broken",
    "cracked screen",
    "needs repair",
    "not tested",
    "as is",
    "repair lot",
    "electronics repair",
    "parts lot",

    # Misspellings / hidden listings
    "iphon",
    "iphne",
    "playstaton",
    "pokeman",
    "pokmon",
    "nintndo",
    "xobx",
    "garag sale",
    "estste sale",
    "movng sale",
    "macbok",
    "labtop",
]
