# Master keyword list for D&J Deal Radar
# Expanding search coverage to increase deal discovery

SEARCH_TERMS = [

    # Electronics / Phones
    "iphone",
    "iphone 13",
    "iphone 12",
    "iphone 11",
    "iphone xr",
    "iphone lot",
    "iphone bundle",
    "broken iphone",
    "iphone cracked",
    "iphone parts",
    "android phone",
    "samsung galaxy",
    "samsung phone",
    "pixel phone",
    "google pixel",
    "oneplus",
    "ipad",
    "ipad air",
    "ipad pro",
    "tablet",
    "macbook",
    "macbook pro",
    "macbook air",
    "gaming laptop",
    "laptop lot",
    "computer bundle",
    "graphics card",
    "rtx",
    "gtx",
    "gpu",
    "nvidia",
    "amd gpu",
    "pc parts",
    "gaming pc",
    "desktop computer",

    # Gaming
    "ps5",
    "ps4",
    "playstation",
    "playstaton",
    "ps$5",
    "ps5 bundle",
    "ps4 bundle",
    "xbox",
    "xbox one",
    "xbox series x",
    "xobx",
    "xbox bundle",
    "nintendo switch",
    "switch bundle",
    "nintndo",
    "gamecube",
    "wii",
    "retro console",
    "retro gaming",
    "video game lot",
    "game lot",
    "controller lot",
    "gaming bundle",

    # Tools
    "milwaukee",
    "dewalt",
    "makita",
    "snap on",
    "snapon",
    "craftsman tools",
    "power tools",
    "tool lot",
    "tool bundle",
    "mechanic tools",
    "impact driver",
    "impact wrench",
    "cordless drill",
    "tool box",
    "rolling toolbox",
    "socket set",
    "air compressor",
    "shop tools",
    "garage tools",

    # Liquidation keywords
    "garage sale",
    "estate sale",
    "moving sale",
    "yard sale",
    "garage cleanout",
    "storage cleanout",
    "basement cleanout",
    "attic cleanout",
    "everything must go",
    "need gone",
    "must sell",
    "make offer",
    "bulk lot",
    "bundle",
    "box of stuff",
    "mixed lot",
    "garage find",
    "attic find",

    # Parts / Repair
    "for parts",
    "doesnt work",
    "not working",
    "broken",
    "cracked screen",
    "needs repair",
    "not tested",
    "as is",
    "repair lot",
    "electronics repair",

    # Cards / Collectibles
    "pokemon cards",
    "pokemon lot",
    "sports cards",
    "baseball cards",
    "basketball cards",
    "football cards",
    "card collection",
    "card lot",
    "vintage cards",
    "hockey cards",
    "michael jordan cards",
    "shaquille oneal cards",
    "ken griffey jr cards",
    "trading cards",

    # Misspellings
    "iphon",
    "iphne",
    "playstaton",
    "pokeman",
    "pokmon",
    "nintndo",
    "xobx",
    "garag sale",
    "estste sale",
    "movng sale",
    "iphon lot",
]